<a href="https://colab.research.google.com/github/shallynagfase9/Data-Science-Assignments/blob/main/Feature_Engineering_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Q1. What is the difference between Ordinal Encoding and Label Encoding? Provide an example of when you might choose one over the other.
"""
Ordinal encoding and label encoding are both techniques used to convert categorical data into numerical form, but they have different applications and implications.

- Ordinal Encoding: Ordinal encoding is specifically used for ordinal categorical variables, where there is a meaningful order or hierarchy among the categories. The numerical labels assigned to the categories reflect this order.
- Label Encoding: Label encoding, on the other hand, can be applied to both ordinal and nominal categorical variables. It assigns a unique numerical label to each category, without considering any inherent order or hierarchy.

"""

In [1]:
# Q2. Explain how Target Guided Ordinal Encoding works and provide an example of when you might use it in a machine learning project.
"""
Steps for Target Guided Ordinal Encoding:
- Grouping by Category: Group the dataset by the categorical variable for which encoding is to be performed.
- Calculate Summary Statistics: For each category, calculate summary statistics of the target variable (e.g., mean, median, etc.). These statistics represent the relationship between the category and the target variable.
- Order Categories: Order the categories based on the computed summary statistics. For example, categories with higher average target variable values may be assigned higher numerical labels.
- Assign Numerical Labels: Assign numerical labels to the categories based on their order. The category with the highest summary statistic value may be assigned the highest label, and so on.
- Encode Data: Replace the categorical variable with the assigned numerical labels in the dataset.
"""

import pandas as pd
df = pd.DataFrame(
    {
        "city":["New York","London","Paris","Tokyo","New York","Paris"],
        "price":[200,150,400,250,170,190]
    }
)

mean_price = df.groupby("city")["price"].mean().to_dict()
mean_price

df["city_encoded"] = df["city"].map(mean_price)

df[["price","city_encoded"]]

price  city_encoded
0    200         185.0
1    150         150.0
2    400         295.0
3    250         250.0
4    170         185.0
5    190         295.0

In [2]:
# Q3. Define covariance and explain why it is important in statistical analysis. How is covariance calculated?

# Covariance is a measure of the relationship between two random variables.
# Covariance is important in statistical analysis, to identify relationship between variables.
import numpy as np

# Example data for two variables X and Y
X = np.array([1, 2, 3, 4, 5])
Y = np.array([5, 4, 3, 2, 1])

# Calculate covariance between X and Y
covariance_matrix = np.cov(X, Y)

# Extract the covariance value from the covariance matrix
covariance_value = covariance_matrix[0, 1]

print("Covariance between X and Y:", covariance_value)


Covariance between X and Y: -2.5


In [ ]:
"""
Q4. For a dataset with the following categorical variables: Color (red, green, blue), Size (small, medium,
large), and Material (wood, metal, plastic), perform label encoding using Python's scikit-learn library.
Show your code and explain the output.
"""
from sklearn.preprocessing import LabelEncoder
import pandas as pd

# Create a DataFrame with categorical variables
data = pd.DataFrame({
    'Color': ['red', 'green', 'blue', 'red', 'green'],
    'Size': ['small', 'medium', 'large', 'medium', 'small'],
    'Material': ['wood', 'metal', 'plastic', 'metal', 'plastic']
})

# Initialize LabelEncoder
label_encoder = LabelEncoder()

# Apply label encoding to each categorical column
for i in data.columns:
  data[i + '_encoded'] = label_encoder.fit_transform(data[i])

print(data)

In [4]:
"""
Q5. Calculate the covariance matrix for the following variables in a dataset: Age, Income, and Education
level. Interpret the results.
"""
import numpy as np

# Example data for Age, Income, and Education level
Age = np.array([30, 40, 50, 45, 35])
Income = np.array([50000, 60000, 70000, 55000, 65000])
Education_Level = np.array([12, 16, 18, 14, 15])

# Stack the variables into a 2D array
data = np.vstack((Age, Income, Education_Level))

# Calculate the covariance matrix
covariance_matrix = np.cov(data)

# Print the covariance matrix
print("Covariance Matrix:")
print(covariance_matrix)

"""
Interpreting the results:

- A positive covariance indicates a positive relationship between variables, meaning they tend to increase or decrease together.
- A negative covariance indicates a negative relationship between variables, meaning one tends to increase while the other decreases.
- The magnitude of covariance values indicates the strength of the relationship between variables. Higher values imply a stronger relationship, while lower values imply a weaker relationship.
However, interpreting the covariance values alone may not provide a complete understanding of the relationship between variables.

"""

Covariance Matrix:
[[6.250e+01 3.750e+04 1.375e+01]
 [3.750e+04 6.250e+07 1.625e+04]
 [1.375e+01 1.625e+04 5.000e+00]]


'\nInterpreting the results:\n\n- A positive covariance indicates a positive relationship between variables, meaning they tend to increase or decrease together.\n- A negative covariance indicates a negative relationship between variables, meaning one tends to increase while the other decreases.\n- The magnitude of covariance values indicates the strength of the relationship between variables. Higher values imply a stronger relationship, while lower values imply a weaker relationship.\nHowever, interpreting the covariance values alone may not provide a complete understanding of the relationship between variables. \n\n'

In [5]:
"""
Q6. You are working on a machine learning project with a dataset containing several categorical
variables, including "Gender" (Male/Female), "Education Level" (High School/Bachelor's/Master's/PhD),
and "Employment Status" (Unemployed/Part-Time/Full-Time). Which encoding method would you use for
each variable, and why?
"""

"""
For the given dataset containing several categorical variables ("Gender", "Education Level", and "Employment Status"),
the choice of encoding method for each variable depends on the nature of the variable and its relationship with the target variable,
as well as the requirements of the machine learning algorithm being used.

Encoding Method: One-Hot Encoding

- One-Hot Encoding is preferred for nominal categorical variables (Gender, Employment Status) to create binary dummy variables without imposing any ordinal relationships among categories.
- Ordinal Encoding is suitable for ordinal categorical variables (Education Level) with a clear hierarchy, allowing the model to capture the order of categories effectively.

"""

'\nFor the given dataset containing several categorical variables ("Gender", "Education Level", and "Employment Status"), \nthe choice of encoding method for each variable depends on the nature of the variable and its relationship with the target variable, \nas well as the requirements of the machine learning algorithm being used.\n\nEncoding Method: One-Hot Encoding\n\n- One-Hot Encoding is preferred for nominal categorical variables (Gender, Employment Status) to create binary dummy variables without imposing any ordinal relationships among categories.\n- Ordinal Encoding is suitable for ordinal categorical variables (Education Level) with a clear hierarchy, allowing the model to capture the order of categories effectively.\n\n'

In [8]:
"""
Q7. You are analyzing a dataset with two continuous variables, "Temperature" and "Humidity", and two
categorical variables, "Weather Condition" (Sunny/Cloudy/Rainy) and "Wind Direction" (North/South/
East/West). Calculate the covariance between each pair of variables and interpret the results.

"""
import numpy as np

# Example data for Temperature and Humidity (continuous variables)
Temperature = np.array([25, 28, 30, 22, 27])  # Example temperatures
Humidity = np.array([60, 65, 70, 55, 62])     # Example humidities

# Calculate the covariance matrix
covariance_matrix = np.cov(Temperature, Humidity)

# Print the covariance matrix
print("Covariance Matrix:")
print(covariance_matrix)

"""
Interpretation:

- A positive covariance between Temperature and Humidity indicates a positive relationship: as Temperature increases, Humidity tends to increase as well, and vice versa.
- The magnitude of covariance (5.5) suggests a moderate positive linear relationship between Temperature and Humidity.
- The covariance matrix provides valuable insights into the relationship between pairs of variables, helping in understanding how changes in one variable are associated with changes in another variable.
"""

Covariance Matrix:
[[ 9.3 16.8]
 [16.8 31.3]]


'\nInterpretation:\n\n- A positive covariance between Temperature and Humidity indicates a positive relationship: as Temperature increases, Humidity tends to increase as well, and vice versa.\n- The magnitude of covariance (5.5) suggests a moderate positive linear relationship between Temperature and Humidity.\n- The covariance matrix provides valuable insights into the relationship between pairs of variables, helping in understanding how changes in one variable are associated with changes in another variable.\n'